### ISSUE TITLE
Inquiry about Generating 'mesh_file' for SPECFEM2D Using MeshAssist

### ISSUE THREAD

**Issue by liaohaiyang1534** [homnath/MeshAssist#36]
Dear Professor Gharti,

I hope this message finds you well. 

I am currently utilizing the MeshAssist software package to convert a 2D mesh from Cubit into the SPECFEM2D format. The process, so far, has been successful and the MeshAssist package has effectively generated several necessary files. However, I seem to have run into a challenge with the 'mesh_file'. 

The 'mesh_file' appears to be a requisite for SPECFEM2D, but it is conspicuously absent from the list of files generated by MeshAssist. 

Given this, I am left wondering: is there a specific command or step within the MeshAssist process to generate the 'mesh_file'? Or is this file supposed to be generated by an entirely different method? 

The collection of files that MeshAssist successfully fabricates are as follows:
![JBNJY%JSKTHINYPFP_UG0K](https://github.com/homnath/MeshAssist/assets/104192749/002e799b-f3e5-4c15-a507-0c633bd78534)

The compilation of files requisite for SPECFEM2D includes:
![ADW4W@9) R(`NOG3RR{ 9 L](https://github.com/homnath/MeshAssist/assets/104192749/b8188425-d18b-4176-9d76-3d3841f38ea4)

Your guidance on this matter would be highly appreciated. I look forward to hearing from you.

Best regards,

Haiyang Liao

**Comment by homnath** [comment]
Hi Haiyang Liao,

*connectivity is the mesh file.

Best,
Hom Nath
________________________________
From: liaohaiyang1534 ***@***.***>
Sent: Sunday, July 16, 2023 10:42 AM
To: homnath/MeshAssist ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [homnath/MeshAssist] Inquiry about Generating 'mesh_file' for SPECFEM2D Using MeshAssist (Issue #36)


Dear Professor Gharti,

I hope this message finds you well.

I am currently utilizing the MeshAssist software package to convert a 2D mesh from Cubit into the SPECFEM2D format. The process, so far, has been successful and the MeshAssist package has effectively generated several necessary files. However, I seem to have run into a challenge with the 'mesh_file'.

The 'mesh_file' appears to be a requisite for SPECFEM2D, but it is conspicuously absent from the list of files generated by MeshAssist.

Given this, I am left wondering: is there a specific command or step within the MeshAssist process to generate the 'mesh_file'? Or is this file supposed to be generated by an entirely different method?

The collection of files that MeshAssist successfully fabricates are as follows:
[JBNJY%JSKTHINYPFP_UG0K]<https://user-images.githubusercontent.com/104192749/253810258-002e799b-f3e5-4c15-a507-0c633bd78534.png>

The compilation of files requisite for SPECFEM2D includes:
***@***.***) R(`NOG3RR{ 9 L]<https://user-images.githubusercontent.com/104192749/253810260-b8188425-d18b-4176-9d76-3d3841f38ea4.png>

Your guidance on this matter would be highly appreciated. I look forward to hearing from you.

Best regards,

Haiyang Liao

**Comment by homnath** [comment]
Resolved.
